# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 944923a9ed8e227c848bc3b643a4f01321a6cb49758abc7eb9e4106a716ecf027f7a80bb481193f9b3422b45dee285306ba0acbe445f8881c3736a47a60b6da3

test:
  secret_key_base: 8dfd1e73eb7e8ab278dae614443339157dd34c308bcf328875c0a73eaada880f3170a4a8cfa6f420b55bed85ae45484b4cb315f78992ce9931501505da5f0174

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
